# Generated by Django 4.1.2 on 2022-10-24 02:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('descricao', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidade', models.CharField(max_length=64, unique=True)),
                ('nome', models.CharField(max_length=128)),
                ('senha', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('impressao_digital', web.models.FingerPrintField(blank=True, help_text='Deixe em branco se não quiser salvar a digital', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.porta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
            ],
            options={
                'verbose_name_plural': 'permissoes',
            },
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('biometria_ou_senha', models.BooleanField(default=True)),
                ('porta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.porta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
            ],
        ),
    ]
