# Generated by Django 4.0.5 on 2022-06-11 22:02

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_usuario_fingerprint_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fingerprint_characteristics',
            field=models.CharField(blank=True, default='', max_length=512, validators=[web.models.validar_impressao_digital]),
            preserve_default=False,
        ),
    ]
