# Generated by Django 4.0.5 on 2022-06-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_usuario_fingerprint_characteristics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fingerprint_characteristics',
            new_name='salvar_digital',
        ),
    ]
