# Generated by Django 4.0.5 on 2022-06-12 22:00

from django.db import migrations
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_usuario_salvar_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='salvar_digital',
            field=web.models.FingerPrintField(blank=True, help_text='Deixe em branco se não quiser salvar a digital', max_length=512),
        ),
    ]
